### PR TITLE
fix test_inject for sub-sub-classes, v1.1.3

### PR DESCRIPTION
**Pull request by nerdrew**

### CODE REVIEW

**Review by zachmargolis — APPROVED** [review]
I feel like we talked about this a million years ago, my goal with the gem was that it was simple enough we wouldn't need a test helper at all... but now that we're here...may as well fix it 
LGTM (tbh I only skimmed it but I trust you)

**Comment by nerdrew** [comment]
@zachmargolis I agree with you :'(

**Comment by nerdrew** [comment]
I'm not sure how to deal with test pollution though. Trying to find the test that injected a mock and then didn't reset it was *very* time consuming in our app...

**Comment by nerdrew** [comment]
I think a better fix for my app would be to remove the writers. The the memoization and lazy initialization bits are simple and useful. We can then stub tests using normal machinery and not test inject anything...

Could always do a v2 that removes the test helper and the writers...

**Comment by zachmargolis** [comment]
> I think a better fix for my app would be to remove the writers. The the memoization and lazy initialization bits are simple and useful. We can then stub tests using normal machinery and not test inject anything...
> 
> Could always do a v2 that removes the test helper and the writers...

Yeah I think in a V2 I'd remove static stuff entirely so it's all instances...

Anyways I think you have merge access here as well as rubygems access, go ahead and bump this if you want! or LMK if you need me to do any of it

**Pull request merged**
