### PR TITLE
define_method is private. Use .send on rspec helpers.

### PR DESCRIPTION
**Pull request by mhickman**

### CODE REVIEW

**Comment by zachmargolis** [comment]
@mhickman thanks! Did this change in a particular version of RSpec? Somehow this used to work... cc @nerdrew

**Comment by nerdrew** [comment]
Hmmm. It looks like it is public...

```ruby
[1] pry(main)> module M; end
=> nil
[2] pry(main)> M.define_method(:m) { }
=> :m
```

What's the problem you ran into?

**Comment by mhickman** [comment]
```
2.4.0 (main):0 > class A; end
=> nil
2.4.0 (main):0 > A.define_method
NoMethodError: private method `define_method' called for A:Class
Did you mean?  define_singleton_method
from (pry):2:in `__pry
```

it's private on class for me

**Comment by nerdrew** [comment]
2.6.0

**Comment by nerdrew** [comment]
LOL. Looks like they made it public in 2.5.

**Comment by zachmargolis** [comment]
🤷‍♂️ seems like it's worth making more compatible. Thanks for the fix! I'll merge.

**Comment by nerdrew** [comment]
Might be worth setting up travis for this repo.

**Pull request merged**
